version: '2.1'
services:
  server:
    image: server
    network_mode: host
    volumes:
      - /root/logs:/var/log/app
        #ports:
        #- "8080:8080"
        #extra_hosts:
      #- "localhost:host-gateway"
    environment:
      - APP_ENV=local
    restart: unless-stopped